### ISSUE TITLE
Add 'make test' target to run tests

### ISSUE THREAD

**Issue by godbyk** [wspr/hardwrap#11]
[Incidentally, qstest looks quite useful. I've been meaning to find a testing framework for my LaTeX cocde for quite a while now. I'll have to explore qstest some more.]

**Comment by wspr** [comment]
I haven't looked too much into it either. Unless it can parse the log file, though, we're not going to be able to add any of the `\pkg@warning`-type tests to the test suite.

I'm going to assign this bug to you `:)`

**Comment by godbyk** [comment]
No problem!

**Comment by godbyk** [comment]
`test` target was added in commit 690e225896dbaf02dbce.
