### ISSUE TITLE
Filtering out "bad" commands

### ISSUE THREAD

**Issue by wspr** [wspr/hardwrap#3]
Would be good to take care of `~`, `\par`, etc, à la hyperref's bookmark string transformations. This is a bit open-ended and no need to go overboard.

Looks like the package to use for that is Heiko's `stringenc`.

**Comment by godbyk** [comment]
Unless I'm missing something, it doesn't appear that `stringenc` does what we want.

**Comment by wspr** [comment]
Oh, sorry! I thought that's where hyperref did its thing. But I think you're right; I tried a couple of things using `\StringEncodingConvert\Result\HelloWorld{ascii}{pdfdoc}` and it doesn't seem to work the way that would be helpful to us :(

I guess it's back to the drawing board. Gotta run for now...

**Comment by wspr** [comment]
This is sort of accounted for now. The facility is there with `\HardWrapSetup` but we don't do much with it. I'm happy to leave it open-ended, but if you'd like to work on it some more, I don't have a problem at all with that.
