### ISSUE TITLE
`\pkg@warning{\protect\LaTeX}` emits `\protect\LaTeX`

### ISSUE THREAD

**Issue by godbyk** [wspr/hardwrap#9]
Test case:

```
\GeneratePackageLogMacros{pkg}
\pkg@warning{\protect\LaTeX}
```

Result:

```
Package pkg Warning: \protect \LaTeX 
```

Expected result:

```
Package pkg Warning: \LaTeX
```

(Why package authors don't just use \string\blah and make my life simpler, I don't know.)

**Comment by wspr** [comment]
code dump

sorry! I was working on this on-and-off today
and the whole thing turned into a mess

I hope this doesn't get in your way too much

closed by 6c0119798d9e755caa1244e3221ea89e0e42cae8
closed by 6c0119798d9e755caa1244e3221ea89e0e42cae8
